### ISSUE TITLE
Provide event for changes to property's `responsibilities`

### ISSUE THREAD

**Issue by ivan-wolf** [Garaio-REM/remcloud-message-bus-api#18]
There's the [Masterdata.ManagementTeam.Updated](https://github.com/Garaio-REM/remcloud-message-bus-api/blob/master/masterdata_context.md#masterdatamanagementteamupdated) event, but since `managementTeam` has been deprecated in the GraphQL API, we've since migrated to using `responsibilities`. So we'd be more interested in changes to `responsibilities` data.

Potential triggers could be (from my limited understanding):

- A user's contact information is changed (basically whatever is exposed through GraphQL).
- A user's role (for the given property) is updated (if the previous and/or new role is mapped to a responsibility).
- The responsibility-to-role mapping is changed (is that done on a property level or globally?).

**Comment by gernotkogler** [comment]
Good point, I will create a ticket for that
